development:
  password: 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
  theme_id: "115068928188"
  store: storetest011.myshopify.com
  proxy: http://localhost:3000
  ignore_files:
    - "*.gif"
    - "*.jpg"
    - config/settings_data.json
production:
  password: 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
  theme_id: "115163365564"
  store: storetest011.myshopify.com
  timeout: 60s
  readonly: true

